# Generated by Django 5.1.7 on 2025-05-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='has_service_center',
            field=models.BooleanField(default=False),
        ),
    ]
