lint_js:
      name: Lint JavaScript Files
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14 # Or 18 or 20 if your project uses a newer Node.js version

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run Linter
        run: |
          # This command finds all JavaScript files recursively (excluding node_modules)
          # and runs JSHint on them using the .jshintrc config.
          find ./server/database -type f -name "*.js" -not -path "*/node_modules/*" -exec jshint --extra-ext .js --config-file .jshintrc {} +
          echo "Linted all the js files successfully"
